name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if your default branch is master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload website files
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./final   # <— make sure your site is inside that folder!

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
